
<?php
return [

     //un-comment if you needed this field
    'users' => [
        [
            'label' => 'Name',
            'name' => 'name',
            'type' => 'text',
            'rules' => 'required|string|max:255',
            'placeholder' => 'Enter Name',
            'input_style' => 'full',
            'visible' => true,
        ],
        [
            'label' => 'Email',
            'name' => 'email',
            'type' => 'email',
            'rules' => 'required|email',
            'placeholder' => 'Enter Email',
            'input_style' => 'full',
            'visible' => true,
            'display_on_create' => true,
            'display_on_edit' => true,
        ],
        // [  
        //     'label' => 'Mobile No.',
        //     'name' => 'mobile_no',
        //     'type' => 'number',
        //     'rules' => 'nullable|numeric|regex:/^[0-9]{10,11}$/',
        //     'placeholder' => 'Enter Mobile No',
        //     'visible' => true,
        //     'display_on_create' => true,
        //     'display_on_edit' => true,
        // ],
        [
            'label' => 'Image',
            'name' => 'image',
            'type' => 'file',
            'visible' => true,
            'upload_type' => 'multiple',
            'placeholder' => 'Image',
            'rules' => 'nullable|image|mimes:jpg,jpeg,png|max:2048',
            'display_on_create' => true,
            'display_on_edit' => true,
        ],
        [
            'label' => 'Gender',
            'name' => 'gender',
            'type' => 'radio',
            'values' => 'male|female|other',
            'default' => 'male',
            'visible' => true,
            'rules' => 'nullable|in:male,female,other',
            'display_on_create' => true,
            'display_on_edit' => true,
        ],
        [
            'label' => 'Language',
            'name' => 'language',
            'type' => 'checkbox',
            'values' => 'gujarati|english|hindi',
            'default' => 'english',
            'visible' => true,
            'rules' => 'nullable|array',
            'language.*' => 'in:gujarati,english,hindi',
            'display_on_create' => true,
            'display_on_edit' => true,
        ],
        // [
        //     'label' => 'Status',
        //     'name' => 'status',
        //     'type' => 'toggle',
        //     'default' => 1,
        //     'visible' => true,
        //     'rules' => 'nullable|boolean',
        //     'display_on_create' => true,
        //     'display_on_edit' => true,
        // ],
        // [
        //     'label' => 'Favorite Color',
        //     'name' => 'favorite_color',
        //     'type' => 'color',
        //     'rules' => 'nullable|string',
        //     'visible' => true,
        //     'placeholder' => '#FFFFFF',
        //     'display_formate' => 'color', // or 'code'
        //     'display_on_create' => true,
        //     'display_on_edit' => true,
        // ],
        // [
        //     'label' => 'Age',
        //     'name' => 'age',
        //     'type' => 'range',
        //     'min' => 0,
        //     'max' => 100,
        //     'step' => 1,
        //     'default' => 25,
        //     'visible' => true,
        //     'rules' => 'nullable|integer|min:0|max:100',
        //     'display_on_create' => true,
        //     'display_on_edit' => true,
        // ],
        // [
        //     'label' => 'Favorite Movie',
        //     'name' => 'favorite_movie',
        //     'type' => 'select',
        //     'default' => 'Harry Potter',
        //     'values' => 'The Lord of the Rings|The Wheel of Time|Harry Potter|Stranger Things',
        //     'rules' => 'nullable|in:The Lord of the Rings,The Wheel of Time,Harry Potter,Stranger Things',
        //     'visible' => true,
        //     'select_type' => 'multiple',
        //     'display_on_create' => true,
        //     'display_on_edit' => true,
        // ],
        // [
        //     'label' => 'Country',
        //     'name' => 'country',
        //     'type' => 'select',
        //     'default' => 'india',
        //     'values' => 'india|u.k|u.s',
        //     'rules' => 'required|in:india,u.k,u.s',
        //     'visible' => true,
        //     'select_type' => 'multiple',
        //     'display_on_create' => true,
        //     'display_on_edit' => true,
        // ],
        [
            'label' => 'City',
            'name' => 'city',
            'type' => 'select',
            'relation' => [
                'table_name' => 'city',
                'label' => 'city_name',
                'values' => 'id',
            ],
            'default' => 'Surat',
            'rules' => 'nullable|in:relation.values',
            'visible' => true,
            'select_type' => 'multiple',
            'display_column' => 'relation.label', // display on Data
            'display_on_create' => true,
            'display_on_edit' => true,
        ],
        // [
        //     'label' => 'Join Date',
        //     'name' => 'join_date',
        //     'type' => 'date',
        //     'rules' => 'nullable|date|before_or_equal:today',
        //     'display_formate' => 'd-F-Y',
        //     'visible' => true,
        //     'display_on_create' => true,
        //     'display_on_edit' => true,
        // ],
        // [
        //     'label' => 'Password',
        //     'name' => 'password',
        //     'type' => 'password',
        //     'rules' => 'nullable|min:6',
        //     'placeholder' => 'Enter password',
        //     'visible' => true,
        //     'display_on_create' => true,
        //     'display_on_edit' => true,
        // ],
    ],

    'posts' => [
        [
            'label' => 'Title',
            'name' => 'title',
            'type' => 'text',
            'rules' => 'required|string|max:255',
            'visible' => true,
        ],
        [
            'label' => 'Content',
            'name' => 'content',
            'type' => 'textarea',
            'rules' => 'required|string',
            'visible' => true,
        ],
        [
            'label' => 'Featured Image',
            'name' => 'featured_image',
            'type' => 'image',
            'upload_type' => 'multiple',
            'rules' => 'nullable|image|mimes:jpeg,png,jpg,gif|max:2048',
            'visible' => true,
        ],
        [
            'label' => 'Published At',
            'name' => 'published_at',
            'type' => 'date',
            'rules' => 'nullable|date',
            'visible' => true,
        ],
    ],

    // added here other array name and array name must be same as table_name and field columns available on the table

];
