
<?php
return [
    'users' => [
        [
            'label' => 'Name',
            'name' => 'name',
            'type' => 'text',
            'rules' => 'required|string|max:255',
            'placeholder' => 'Enter Name',
            'visible' => true,
        ],
        [
            'label' => 'Email',
            'name' => 'email',
            'type' => 'email',
            'rules' => 'required|email',
            'placeholder' => 'Enter Email',
            'visible' => true,

        ],
        [
            'label' => 'Mobile No.',
            'name' => 'mobile_no',
            'type' => 'number',
            'rules' => 'required|numeric|regex:/^[0-9]{10,11}$/',
            'placeholder' => 'Enter Mobile No',
            'visible' => true,
        ],
        [
            'label' => 'Image',
            'name' => 'image',
            'type' => 'file',
            'visible' => true,
            'upload_type' => 'single',
            'placeholder' => 'Image',
            'rules' => 'nullable|image|mimes:jpg,jpeg,png|max:2048',
        ],
        [
            'label' => 'Gender',
            'name' => 'gender',
            'type' => 'radio',
            'values' => 'male|female|other',
            'default' => 'male',
            'visible' => true,
            'rules' => 'nullable|in:male,female,other',
        ],
        [
            'label' => 'Language',
            'name' => 'language',
            'type' => 'checkbox',
            'values' => 'gujarati|english|hindi',
            'default' => 'english',
            'visible' => true,
            'rules' => 'nullable|array',
            'language.*' => 'in:gujarati,english,hindi',
        ],
        [
            'label' => 'Status',
            'name' => 'status',
            'type' => 'toggle',
            'default' => 1,
            'visible' => true,
            'rules' => 'nullable|boolean',
        ],
        [
            'label' => 'Favorite Color',
            'name' => 'favorite_color',
            'type' => 'color',
            'rules' => 'nullable|string',
            'visible' => true,
            'placeholder' => '#FFFFFF',
            'display_formate' => 'color', // or 'code'
        ],
        [
            'label' => 'Age',
            'name' => 'age',
            'type' => 'range',
            'min' => 0,
            'max' => 100,
            'step' => 1,
            'default' => 25,
            'visible' => true,
            'rules' => 'nullable|integer|min:0|max:100',
        ],
        [
            'label' => 'City',
            'name' => 'city',
            'type' => 'select',
            'values' => 'surat|vapi|vadodara|ahmedabad|rajkot',
            'default' => 'surat',
            'rules' => 'required|in:surat,vapi,vadodara,ahmedabad,rajkot',
            'visible' => true,
        ],
        [
            'label' => 'Join Date',
            'name' => 'join_date',
            'type' => 'date',
            'rules' => 'required|date|before_or_equal:today',
            'display_formate' => 'd-F-Y',
            'visible' => true,
        ],
        [
            'label' => 'Password',
            'name' => 'password',
            'type' => 'password',
            'rules' => 'required|min:6',
            'placeholder' => 'Enter password',
            'visible' => false,
        ],
    ],

    'posts' => [
        [
            'label' => 'Post Name',
            'name' => 'post_name',
            'type' => 'text',
            'visible' => true,
            'placeholder' => 'Enter post name',
            'rules' => 'required|string|min:3',
        ],
        [
            'label' => 'Content',
            'name' => 'content',
            'type' => 'textarea',
            'placeholder' => 'enter content',
            'visible' => true,
            'rules' => 'required|string|min:10',
        ],
        [
            'label' => 'image',
            'name' => 'image',
            'type' => 'file',
            'visible' => true,
            'upload_type' => 'multiple',
            'rules' => 'nullable|image|mimes:jpg,jpeg,png|max:2048',
        ],
    ],

];
